### ISSUE TITLE
auto-mode-alist error

### ISSUE THREAD

**Issue by windtail** [delaanthonio/kconfig-mode#1]
(add-to-list 'auto-mode-alist '("\\Kconfig\\" . kconfig-mode))
There should be a ' at the end of regex

**Comment by windtail** [comment]
it will prevent me opening any file in emacs 25.3 after load this module, to match exactly Kconfig the regex should be /Kconfig\\\\'

**Comment by delaanthonio** [comment]
38acec1 Should fix this issue.
